### ISSUE TITLE
Seq.App.Atlassian.Jira 0.2.5/0.2.6 NuGet package missing Handlebars.dll

### ISSUE THREAD

**Issue by MattMofDoom** [aliozgur/SeqApps#13]
Hi @aliozgur, 

I noted this on #12 but just in case you don't see it - the 0.2.5 NuGet package is missing Handlebars.dll, so the app fails when installed to Seq. I normally use Appveyor to build, test, and publish to NuGet so I setup the project the same as my apps to automatically include it when the NuGet package is built, but assume you're generating it differently (eg. With a nuspec) and that it's missing out the dependency.

![126874241-b680b7b2-177b-485c-80e6-207b0085494f.png](https://user-images.githubusercontent.com/30714560/126874797-b510bc54-1160-473b-90ba-d055b0b6d9e8.png)

Cheers,

Matt

**Comment by MattMofDoom** [comment]
@aliozgur You're probably still looking into this, but I noticed the 0.2.6 package on Nuget and tested - still the same issue with Handlebars missing ☹

If I open the .nupkg of my test build, I see the below. Believe the only essential ones are Handlebars, Seq.App.Jira, and SeqApps.Commons. 

 
![image](https://user-images.githubusercontent.com/30714560/126875766-d42fbb48-03ed-451e-b2f1-52922e0d241b.png)

Your 0.4.6 package only contains Seq.App.Jira.

![image](https://user-images.githubusercontent.com/30714560/126875799-ec0b8df0-3815-42e7-947a-c77bc5227602.png)

May need something like https://thewissen.io/packaging-legacy-dlls-nuget/ for packing with a .nuspec, and pointing at the appropriate release path for the DLLs. 

FWIW - I fetched and merged your master back to my fork, and if I build it in Visual Studio with "Generate Nuget package on build" left enabled, the resulting .nupkg in the release folder is correct, so that might also be an option for a manual upload to Nuget, although you'll probably want to correct the package version 😊

**Comment by MattMofDoom** [comment]
@aliozgur  Never mind - looks like you've sorted it out with 0.2.7. Will test 😊

**Comment by MattMofDoom** [comment]
@aliozgur Looks like the Handlebars issue is resolved in 0.2.7, but there is an error when posting to Jira in loading Newtonsoft.Json.dll v13.0.0.0.

![image](https://user-images.githubusercontent.com/30714560/126876526-09f0c5c9-a18f-4060-a48b-925c4befb9f7.png)

Looking at the .nupkg, it appears that the v13.0.1.25517 version has been packaged, instead of the expected v12.0.3.23909. Not sure how - checked the Nuget package manager and it's still at v12.0.3, which is right for the current release of Seq. I checked the version included in the release folder and it's v12, so I guess it's being drawn from elsewhere?

**Comment by aliozgur** [comment]
@MattMofDoom I'll look into this as well

**Comment by aliozgur** [comment]
@MattMofDoom  0.2.8 published. Can you please check and let me know the result.

**Comment by MattMofDoom** [comment]
Hi @aliozgur,

It's still referencing Newtonsoft.Json 13.0.

After completing a fetch and pull to my local machine, I now see the issue - the version in Nuget Package Manager had been updated to 13.0.1. 

I see you want to add project key property mapping but it looks like it could use a little bit more code to work as intended. I'll send a fresh pull after I've corrected the Newtonsoft.Json issue and tweaked this 😊

Cheers,

Matt

**Comment by MattMofDoom** [comment]
@aliozgur  Found the issue. SeqApps.Common was still referencing Newtonsoft.Json 13.0.1.

I've added the setting for project key property which allows the project key setting to act as a fallback if the property isn't matched. 

Pull request coming shortly.
