### ISSUE TITLE
Nuget 0.2.12 missing Handlebars and SeqApps.Common

### ISSUE THREAD

**Issue by MattMofDoom** [aliozgur/SeqApps#19]
Hey @aliozgur ,

The nuget package for 0.2.12 is missing dependencies again.

Size 70kb, should be ~184kb.

Inspecting the package, Handlebars.dll and SeqApps.Common.dll are missing.

Cheers,

Matt

**Comment by aliozgur** [comment]
Weird, no changes in csproj file. I'm looking into this.

**Comment by aliozgur** [comment]
If GeneratePackageOnBuild is set to true, VS does not take includes into account while generating the package during the build process. So I  changed GeneratePackageOnBuild value to false. The order is build the project then run the pack command.
