### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies

### ISSUE THREAD

**Issue by agrynco** [aliozgur/SeqApps#3]
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Seq.App.Jira.JiraIssueReactor.<CreateIssue>d__57.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

**Comment by aliozgur** [comment]
@agrynco who throws this exception?

**Comment by aliozgur** [comment]
New version published on nuget.org. Please try to install the latest version and see if your problem is fixed.

**Comment by aliozgur** [comment]
Jira, GitLab abd GitHub apps were updated to .NET SDK style projects and latest version published on NuGet
